services:
  subnet1:
    image: xinfinorg/xdcsubnets:v0.3.2
    volumes:
      - xdcchain1_data:/work/xdcchain
      - ${HOSTPWD}/genesis.json:/work/genesis.json
    restart: always
    env_file:
      - subnet1.env
    profiles:
      - machine1
    ports:
      - 20303:20303/tcp
      - 20303:20303/udp
      - 8545:8545/tcp
      - 8545:8545/udp
      - 9555:9555/tcp
      - 9555:9555/udp
    networks:
      docker_net:
        ipv4_address: 192.168.25.11
  subnet2:
    image: xinfinorg/xdcsubnets:v0.3.2
    volumes:
      - xdcchain2_data:/work/xdcchain
      - ${HOSTPWD}/genesis.json:/work/genesis.json
    restart: always
    env_file:
      - subnet2.env
    profiles:
      - machine1
    ports:
      - 20304:20304/tcp
      - 20304:20304/udp
      - 8546:8546/tcp
      - 8546:8546/udp
      - 9556:9556/tcp
      - 9556:9556/udp
    networks:
      docker_net:
        ipv4_address: 192.168.25.12
  subnet3:
    image: xinfinorg/xdcsubnets:v0.3.2
    volumes:
      - xdcchain3_data:/work/xdcchain
      - ${HOSTPWD}/genesis.json:/work/genesis.json
    restart: always
    env_file:
      - subnet3.env
    profiles:
      - machine1
    ports:
      - 20305:20305/tcp
      - 20305:20305/udp
      - 8547:8547/tcp
      - 8547:8547/udp
      - 9557:9557/tcp
      - 9557:9557/udp
    networks:
      docker_net:
        ipv4_address: 192.168.25.13
  bootnode:
    image: xinfinorg/xdcsubnets:v0.3.1
    restart: always
    env_file: common.env
    volumes:
      - ${HOSTPWD}/bootnodes:/work/bootnodes
    entrypoint:
      - bash
      - /work/start-bootnode.sh
    command:
      - '-verbosity'
      - '6'
      - '-nodekey'
      - bootnode.key
    ports:
      - 20301:20301/tcp
      - 20301:20301/udp
    profiles:
      - machine1
    networks:
      docker_net:
        ipv4_address: 192.168.25.51
  relayer:
    image: xinfinorg/xdc-relayer:v0.3.1
    restart: always
    env_file: common.env
    ports:
      - '5215:5215'
    profiles:
      - services
    networks:
      docker_net:
        ipv4_address: 192.168.25.52
  stats:
    image: xinfinorg/subnet-stats-service:v0.1.11
    restart: always
    env_file: common.env
    volumes:
      - ${HOSTPWD}/stats-service/logs:/app/logs
    ports:
      - '5213:5213'
    profiles:
      - services
    networks:
      docker_net:
        ipv4_address: 192.168.25.53
  frontend:
    image: xinfinorg/subnet-frontend:v0.1.12
    restart: always
    env_file: common.env
    volumes:
      - ${HOSTPWD}/common.env:/app/.env.local
    ports:
      - '5214:5214'
    profiles:
      - services
    networks:
      docker_net:
        ipv4_address: 192.168.25.54
  subswap_frontend:
    image: xinfinorg/subswap-frontend:v0.1.0
    restart: always
    volumes:
      - >-
        ${HOSTPWD}/subswap-frontend.config.json:/app/subswap-frontend.config.json
    ports:
      - '5216:5216'
    profiles:
      - subswap
    networks:
      docker_net:
        ipv4_address: 192.168.25.55
volumes:
  xdcchain1_data:
    driver: local
  xdcchain2_data:
    driver: local
  xdcchain3_data:
    driver: local

networks:
  docker_net:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.25.0/24
